name: UpdateTestRepos

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: next
    - uses: actions/setup-node@v4
    - run: git config user.email "david@dlaa.me"
    - run: git config user.name "David Anson"
    - run: git checkout -b update-test-repos-$GITHUB_RUN_ID
    - run: npm install
    - run: npm run update-test-repos
      continue-on-error: true
    - run: exit 0
      if: ${{ success() }}
    - run: git add .
    - run: git commit -m "Update test repo snapshots."
    - run: git push --set-upstream origin update-test-repos-$GITHUB_RUN_ID
    - run: gh pr create --base next --body "" --title "Update test repo snapshots." --draft
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
