name: UpdateTestRepos

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: utr
        # RESTORE NEXT LINE ABOVE
        # ref: next
    - uses: actions/setup-node@v4
    - run: git config user.email "david@dlaa.me"
    - run: git config user.name "David Anson"
    - run: git checkout -b update-test-repos-$GITHUB_RUN_ID
    - run: npm install
    # REMOVE NEXT LINE
    - run: node scripts/index.mjs delete test/markdownlint-test-repos-dotnet-docs.mjs test/markdownlint-test-repos-mdn-content.mjs
    - run: npm run clone-test-repo
    # - run: npm run update-test-repos
    - run: ava --timeout=11m --update-snapshots test/markdownlint-test-repos-small.mjs
      continue-on-error: true
    - run: exit 0
      if: ${{ success() }}
    - run: git add .
    - run: git commit -m "Update test repo snapshots."
    - run: git push --set-upstream origin update-test-repos-$GITHUB_RUN_ID
    # BLOCKED: https://github.com/cli/cli/issues/10093
    # - run: gh pr create --base next --body "" --title "Update test repo snapshots." --draft
      # env:
        # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
